[build]
builder = "nixpacks"
buildCommand = "python -m pip install -r backend/requirements.txt"

[deploy]
startCommand = "gunicorn config.wsgi:application --bind 0.0.0.0:${PORT} --chdir backend"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
