# Generated by Django 6.0.6 on 2026-06-07 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('invert', models.BooleanField(default=False)),
                ('color', models.CharField(blank=True, max_length=16)),
                ('icon', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=10)),
                ('area', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(max_length=160)),
                ('detail', models.TextField(blank=True)),
                ('metric', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='companies.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('activo', 'Activo'), ('cerrado', 'Cerrado')], default='activo', max_length=12)),
                ('ai_generated', models.BooleanField(default=False)),
                ('scale_max', models.PositiveSmallIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='companies.company')),
                ('modules', models.ManyToManyField(blank=True, related_name='forms', to='forms.module')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('ord', models.PositiveIntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='forms.form')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='form_questions', to='forms.module')),
            ],
            options={
                'ordering': ['ord', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ModuleQuestion',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('ord', models.PositiveIntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='forms.module')),
            ],
            options={
                'ordering': ['ord'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(blank=True, max_length=160)),
                ('area', models.CharField(blank=True, max_length=120)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='companies.company')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='companies.employee')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='forms.form')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.module')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='forms.response')),
            ],
        ),
        migrations.CreateModel(
            name='ResponseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField()),
                ('form_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.formquestion')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='forms.response')),
            ],
        ),
    ]
