# Generated by Django 6.0.6 on 2026-06-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_aiconversation_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formquestion',
            name='options',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formquestion',
            name='question_type',
            field=models.CharField(default='scale', max_length=20),
        ),
        migrations.AddField(
            model_name='responsedetail',
            name='text_value',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='responsedetail',
            name='value',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
