# Generated by Django 6.0.6 on 2026-06-09 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_form_recipients(apps, schema_editor):
    Form = apps.get_model("forms", "Form")
    FormRecipient = apps.get_model("forms", "FormRecipient")
    Employee = apps.get_model("companies", "Employee")

    for form in Form.objects.select_related("company").all():
        if FormRecipient.objects.filter(form_id=form.id).exists():
            continue

        employee_ids = list(
            Employee.objects.filter(company_id=form.company_id).values_list("id", flat=True)
        )
        if not employee_ids:
            continue

        FormRecipient.objects.bulk_create(
            [FormRecipient(form_id=form.id, employee_id=employee_id) for employee_id in employee_ids],
            ignore_conflicts=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_employee_user'),
        ('forms', '0003_form_deadline_formquestion_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_forms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='formquestion',
            name='question_type',
            field=models.CharField(choices=[('scale', 'Escala 1-5'), ('boolean', 'Verdadero/Falso'), ('multiple', 'Opción múltiple'), ('open', 'Abierta')], default='scale', max_length=20),
        ),
        migrations.CreateModel(
            name='FormRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado')], default='pending', max_length=12)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_recipients', to='companies.employee')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='forms.form')),
            ],
            options={
                'ordering': ['employee__department__name', 'employee__role_title', 'employee__full_name'],
                'unique_together': {('form', 'employee')},
            },
        ),
        migrations.RunPython(backfill_form_recipients, migrations.RunPython.noop),
    ]
