package dev.blendemotes.core.pose;

import dev.blendemotes.core.TestRunner;
import dev.blendemotes.core.anim.Animation;
import dev.blendemotes.core.anim.io.BedrockAnimationLoader;
import dev.blendemotes.core.json.Json;
import dev.blendemotes.core.json.JsonUtil;
import dev.blendemotes.core.math.Mat4;
import dev.blendemotes.core.math.Vec3;
import dev.blendemotes.core.rig.PlayerPart;
import dev.blendemotes.core.rig.RigDefinition;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/**
 * Compares the pose computed from the exported .json against the bone matrices Blender
 * itself computes for the same frames (generated by tools/blender/sample_ground_truth.py).
 */
public class BlenderGroundTruthTest {
    /** Blender armature space (units, Z up) -> Minecraft model space (pixels, Y down). */
    private static final Mat4 C = Mat4.fromRows(new double[][]{
            {4, 0, 0, 0},
            {0, 0, -4, 24},
            {0, 4, 0, 0},
            {0, 0, 0, 1}});
    private static final Mat4 C_INV = C.invertAffine();

    private static final String[] BONES = {
            "body", "body_control", "waist", "torso", "torso_bend", "head", "cape", "cape_bend",
            "left_arm", "left_arm_bend", "left_item", "right_arm", "right_arm_bend", "right_item",
            "left_leg", "left_leg_bend", "right_leg", "right_leg_bend"};

    private static Map<String, Object> truth;

    private static synchronized Map<String, Object> truth() {
        if (truth == null) {
            truth = JsonUtil.asObject(Json.parse(TestRunner.resource("/blender/truth.json")), "truth");
        }
        return truth;
    }

    static Animation load(String name) {
        Map<String, Object> root = JsonUtil.asObject(Json.parse(TestRunner.resource("/blender/" + name + ".json")), "root");
        List<BedrockAnimationLoader.Entry> entries = BedrockAnimationLoader.load(root);
        TestRunner.check(entries.size() == 1, "one animation per file");
        return entries.get(0).animation;
    }

    private static Mat4 matrix(Object rows) {
        List<Object> r = JsonUtil.asArray(rows, "matrix");
        double[][] m = new double[4][4];
        for (int i = 0; i < 4; i++) {
            List<Object> row = JsonUtil.asArray(r.get(i), "row");
            for (int j = 0; j < 4; j++) {
                m[i][j] = ((Number) row.get(j)).doubleValue();
            }
        }
        return Mat4.fromRows(m);
    }

    /** Our transform for a Blender bone name. */
    private static Mat4 ours(PoseEvaluator e, Mat4 root, String bone) {
        if (bone.equals("body")) {
            return new Mat4(root);
        }
        if (bone.endsWith("_bend")) {
            String part = bone.substring(0, bone.length() - 5);
            return root.mul(e.world(part)).mul(e.bendSegment(part));
        }
        return root.mul(e.world(bone));
    }

    /** Max distance (px) between where both transforms put a few points of the bone. */
    private static double pointError(Mat4 a, Mat4 b, Mat4 restBl) {
        Mat4 rest = C.mul(restBl);
        double err = 0;
        double[][] local = {{0, 0, 0}, {0, 1, 0}, {0.5, 0, 0}, {0, 0, 0.5}, {-0.5, 0.5, -0.5}};
        for (double[] p : local) {
            Vec3 restPoint = rest.transformPoint(p[0], p[1], p[2]);
            Vec3 pa = a.transformPoint(restPoint);
            Vec3 pb = b.transformPoint(restPoint);
            err = Math.max(err, pa.sub(pb).length());
        }
        return err;
    }

    private static double[] compare(String action, String mode, boolean print) {
        Map<String, Object> actions = JsonUtil.getObject(truth(), "actions");
        Map<String, Object> act = JsonUtil.getObject(actions, action);
        Map<String, Object> rest = JsonUtil.getObject(truth(), "rest");
        double fps = JsonUtil.getDouble(truth(), "fps", 24);
        Animation anim = load(action);
        VanillaPose vanilla = new VanillaPose().reset(RigDefinition.BLENDER);

        Map<String, Double> worst = new LinkedHashMap<String, Double>();
        Map<String, Double> worstFrame = new LinkedHashMap<String, Double>();
        double sum = 0;
        int count = 0;
        for (Object frameObj : JsonUtil.asArray(act.get(mode), mode)) {
            Map<String, Object> frame = JsonUtil.asObject(frameObj, "frame");
            double f = JsonUtil.getDouble(frame, "frame", 0);
            double t = f / fps;
            PoseEvaluator e = PoseEvaluator.create(anim, t, vanilla, RigDefinition.BLENDER);
            Mat4 root = e.local(PoseEvaluator.BODY);
            Map<String, Object> bones = JsonUtil.getObject(frame, "bones");
            for (String bone : BONES) {
                Mat4 restBl = matrix(rest.get(bone));
                Mat4 blender = C.mul(matrix(bones.get(bone)).mul(restBl.invertAffine())).mul(C_INV);
                Mat4 mine = ours(e, root, bone);
                double err = pointError(blender, mine, restBl);
                sum += err;
                count++;
                if (!worst.containsKey(bone) || err > worst.get(bone)) {
                    worst.put(bone, err);
                    worstFrame.put(bone, f);
                }
            }
        }
        double max = 0;
        for (Map.Entry<String, Double> w : worst.entrySet()) {
            max = Math.max(max, w.getValue());
            if (print) {
                System.out.printf(Locale.ROOT, "    %-10s %-7s %-15s max %.4f px (frame %.2f)%n", action, mode, w.getKey(), w.getValue(), worstFrame.get(w.getKey()));
            }
        }
        System.out.printf(Locale.ROOT, "    %s/%s: max error %.4f px, mean %.4f px over %d bone samples%n", action, mode, max, sum / count, count);
        return new double[]{max, sum / count};
    }

    public void testCartwheelMatchesExportedCurves() {
        double[] e = compare("cartwheel", "export", true);
        TestRunner.check(e[0] < 0.05, "cartwheel deviates from Blender by " + e[0] + " px");
    }

    public void testInchwormMatchesExportedCurves() {
        double[] e = compare("inchworm", "export", true);
        TestRunner.check(e[0] < 0.05, "inchworm deviates from Blender by " + e[0] + " px");
    }

    public void testFullRigReport() {
        // Whole pipeline including the exporter's curve fitting of the IK. The cartwheel uses the
        // rig's "vanilla" mode (straight limbs following the IK end), so only its root/torso
        // bones are comparable with the IK-driven rig; it is printed for information.
        compare("cartwheel", "rig", false);
        double[] b = compare("inchworm", "rig", false);
        TestRunner.check(b[0] < 0.5 && b[1] < 0.05, "inchworm deviates from the full rig: " + b[0] + " / " + b[1]);
    }

    public void testPartTransformsAreConsistent() {
        Animation anim = load("inchworm");
        PlayerPose pose = PoseEvaluator.evaluate(anim, 0.6, new VanillaPose(), new PlayerPose());
        for (PlayerPart p : PlayerPart.VALUES) {
            Mat4 fromTransform = pose.transform(p).toMatrix();
            Vec3 pv = p.defaultPivot;
            Mat4 expected = pose.matrix(p).mul(Mat4.translation(pv.x, pv.y, pv.z));
            TestRunner.check(fromTransform.approxEquals(expected, 1e-6), "decomposition of " + p + " differs: " + fromTransform + " vs " + expected);
        }
    }
}
